import type { ScriptTemplate } from '../types';

export const SCRIPT_TEMPLATES: ScriptTemplate[] = [
  {
    id: 'template-venda',
    name: 'Venda consultiva',
    category: 'venda',
    description: 'Estrutura direta para oferta, dor e chamada para conversa.',
    script: {
      title: 'Roteiro de venda',
      theme: 'Oferta',
      audience: 'Lead qualificado',
      tone: 'Consultivo e objetivo',
      hook: 'Abra com uma dor concreta que o cliente reconhece nos primeiros segundos.',
      development: 'Mostre a consequência da dor, apresente a solução e conecte com um caso ou prova simples.',
      cta: 'Convide para uma conversa direta ou para clicar no link de contato.',
      notes: 'Manter ritmo firme e evitar explicações longas.',
      referenceLink: '',
    },
  },
  {
    id: 'template-institucional',
    name: 'Institucional',
    category: 'institucional',
    description: 'Apresenta autoridade, posicionamento e diferenciais da marca.',
    script: {
      title: 'Roteiro institucional',
      theme: 'Marca',
      audience: 'Público geral',
      tone: 'Confiante e profissional',
      hook: 'Comece com uma frase que resuma o valor central da empresa.',
      development: 'Explique o que a marca faz, para quem faz e por que isso importa no mercado.',
      cta: 'Reforce o convite para conhecer a empresa ou iniciar contato.',
      notes: 'Usar imagens de bastidores, equipe e entregas reais.',
      referenceLink: '',
    },
  },
  {
    id: 'template-reels',
    name: 'Reels curto',
    category: 'reels',
    description: 'Roteiro rápido para retenção nos primeiros segundos.',
    script: {
      title: 'Reels de impacto',
      theme: 'Conteúdo curto',
      audience: 'Instagram/TikTok',
      tone: 'Ágil e provocativo',
      hook: 'Use uma pergunta ou afirmação forte que quebre uma crença comum.',
      development: 'Entregue três pontos curtos, cada um com uma frase simples e visual.',
      cta: 'Peça uma ação única: comentar, salvar, enviar ou chamar no direct.',
      notes: 'Cortes rápidos e frases com pausas marcadas.',
      referenceLink: '',
    },
  },
  {
    id: 'template-aula',
    name: 'Aula',
    category: 'aula',
    description: 'Organiza explicação didática com introdução, blocos e conclusão.',
    script: {
      title: 'Roteiro de aula',
      theme: 'Educação',
      audience: 'Alunos ou audiência técnica',
      tone: 'Didático e claro',
      hook: 'Apresente o problema que a aula resolve e o resultado esperado.',
      development: 'Divida o conteúdo em blocos com exemplos, transições e uma síntese final.',
      cta: 'Convide para revisar o material, praticar ou avançar para a próxima etapa.',
      notes: 'Marcar pausas para exemplos e demonstrações.',
      referenceLink: '',
    },
  },
  {
    id: 'template-podcast',
    name: 'Podcast',
    category: 'podcast',
    description: 'Estrutura tópicos de conversa e passagens naturais.',
    script: {
      title: 'Roteiro de podcast',
      theme: 'Conversa guiada',
      audience: 'Ouvintes do episódio',
      tone: 'Natural e profundo',
      hook: 'Abra com uma provocação ou história curta que antecipa o tema.',
      development: 'Liste blocos de conversa, perguntas de apoio e pontos de transição.',
      cta: 'Finalize retomando a principal ideia e direcionando para o próximo contato.',
      notes: 'Não ler de forma rígida; usar como guia de condução.',
      referenceLink: '',
    },
  },
  {
    id: 'template-anuncio',
    name: 'Anúncio',
    category: 'anuncio',
    description: 'Formato para mídia paga com promessa, prova e ação.',
    script: {
      title: 'Roteiro de anúncio',
      theme: 'Campanha paga',
      audience: 'Público segmentado',
      tone: 'Direto e persuasivo',
      hook: 'Comece com a promessa ou dor principal sem rodeios.',
      development: 'Apresente benefício, prova e objeção principal em frases curtas.',
      cta: 'Direcione para clique, cadastro ou conversa com urgência moderada.',
      notes: 'Gravar variações do gancho para teste A/B.',
      referenceLink: '',
    },
  },
];
