import type { ScriptTemplate } from '../types';

export const SCRIPT_TEMPLATES: ScriptTemplate[] = [
  {
    id: 'template-carrossel',
    name: 'Carrossel',
    category: 'carrossel',
    description: 'Sequencia para educar, prender leitura e fechar com acao.',
    script: {
      title: 'Carrossel',
      theme: 'Conteudo educativo',
      audience: 'Instagram',
      tone: 'Claro e direto',
      hook: 'Slide 1 com promessa objetiva ou dor reconhecivel.',
      development: 'Organize os slides em ideia central, contexto, passos praticos e prova simples.',
      cta: 'Feche com uma acao unica: salvar, comentar, enviar ou chamar no direct.',
      notes: 'Cada slide deve ter uma ideia principal e texto curto.',
      referenceLink: '',
    },
  },
  {
    id: 'template-story',
    name: 'Story',
    category: 'story',
    description: 'Formato rapido para sequencia vertical e interacao.',
    script: {
      title: 'Story',
      theme: 'Atualizacao rapida',
      audience: 'Seguidores ativos',
      tone: 'Natural e proximo',
      hook: 'Comece com uma frase curta que gere curiosidade.',
      development: 'Divida em 3 a 5 telas com pergunta, contexto, bastidor e prova visual.',
      cta: 'Use enquete, resposta no direct ou clique no link.',
      notes: 'Priorizar falas curtas e ritmo de conversa.',
      referenceLink: '',
    },
  },
  {
    id: 'template-post-estatico',
    name: 'Post estático',
    category: 'post_estatico',
    description: 'Legenda e ideia visual para peca unica.',
    script: {
      title: 'Post estático',
      theme: 'Mensagem principal',
      audience: 'Instagram/LinkedIn',
      tone: 'Objetivo e institucional',
      hook: 'Defina uma chamada forte para a arte.',
      development: 'Explique o contexto na legenda com beneficio, detalhe e prova.',
      cta: 'Direcione para comentario, direct, link ou proxima acao comercial.',
      notes: 'Pensar em titulo curto para a arte e legenda complementar.',
      referenceLink: '',
    },
  },
  {
    id: 'template-reels',
    name: 'Reels',
    category: 'reels',
    description: 'Roteiro curto para retencao nos primeiros segundos.',
    script: {
      title: 'Reels',
      theme: 'Conteudo curto',
      audience: 'Instagram/TikTok',
      tone: 'Agil e provocativo',
      hook: 'Use uma pergunta ou afirmacao forte que quebre uma crenca comum.',
      development: 'Entregue tres pontos curtos, cada um com uma frase simples e visual.',
      cta: 'Peca uma acao unica: comentar, salvar, enviar ou chamar no direct.',
      notes: 'Cortes rapidos e frases com pausas marcadas.',
      referenceLink: '',
    },
  },
  {
    id: 'template-youtube',
    name: 'YouTube',
    category: 'youtube',
    description: 'Estrutura para video longo com blocos e retencao.',
    script: {
      title: 'YouTube',
      theme: 'Video longo',
      audience: 'Inscritos e busca',
      tone: 'Didatico e envolvente',
      hook: 'Abra com o problema, promessa e motivo para assistir ate o fim.',
      development: 'Separe introducao, blocos principais, exemplos, transicoes e resumo final.',
      cta: 'Convide para inscricao, comentario ou proximo video relacionado.',
      notes: 'Marcar capitulos e pontos de B-roll.',
      referenceLink: '',
    },
  },
  {
    id: 'template-podcast',
    name: 'Podcast',
    category: 'podcast',
    description: 'Estrutura topicos de conversa e passagens naturais.',
    script: {
      title: 'Podcast',
      theme: 'Conversa guiada',
      audience: 'Ouvintes do episodio',
      tone: 'Natural e profundo',
      hook: 'Abra com uma provocacao ou historia curta que antecipa o tema.',
      development: 'Liste blocos de conversa, perguntas de apoio e pontos de transicao.',
      cta: 'Finalize retomando a principal ideia e direcionando para o proximo contato.',
      notes: 'Nao ler de forma rigida; usar como guia de conducao.',
      referenceLink: '',
    },
  },
  {
    id: 'template-outdoor',
    name: 'Outdoor',
    category: 'outdoor',
    description: 'Mensagem curta para leitura rapida em midia externa.',
    script: {
      title: 'Outdoor',
      theme: 'Campanha externa',
      audience: 'Publico em deslocamento',
      tone: 'Memoravel e direto',
      hook: 'Defina uma frase central com poucas palavras.',
      development: 'Inclua apenas apoio essencial: marca, diferencial ou localizacao.',
      cta: 'Use uma chamada simples: visite, ligue, acesse ou lembre da marca.',
      notes: 'A mensagem precisa funcionar em leitura de poucos segundos.',
      referenceLink: '',
    },
  },
];
